Models/ErrorViewModel.cs
using System;

namespace LostInTheWoods.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Trail.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace LostInTheWoods.Models
{
    public class Trail
    {
        //Trail ID----------
        public int ID {get; set;}

        //----------Trail Name----------
        [Required(ErrorMessage = "Trail name is required!")]
        public string Name {get; set;}

        //----------Trail Description----------
        [Required(ErrorMessage = "Description is required!")]
        [MinLength(10, ErrorMessage= "Description must contain at least 10 characters!")]
        public string Description {get; set;}

        //----------Trail Length----------
        [Required(ErrorMessage = "Trail length is required!")]
        [Range(0, int.MaxValue, ErrorMessage = "Lenght of trail can not be negative!")]
        [RegularExpression("^[0-9-]*$", ErrorMessage = "Length must be numeric!")]
        public double? Length {get; set;}

        //----------Trail Elevation----------
        [Required(ErrorMessage = "Elevation change is required!")]
        [Range(0, int.MaxValue, ErrorMessage = "Elevation change can not be negative!")]
        [RegularExpression("^[0-9-]*$", ErrorMessage = "Elevation change must be numeric!")]
        public int? Elevation {get; set;}

        //----------Trail Longitude----------
        [Required(ErrorMessage = "Longitude is required!")]
        [Range(-180.0, 180.0, ErrorMessage = "Longitude must range from -180.0 to 180.0!")]
        public double? Longitude {get; set;}

        //----------Trail Latitude----------
        [Required(ErrorMessage = "Latitude is required!")]
        [Range(-90.0, 90.0, ErrorMessage = "Latitude must range from -90.0 to 90.0!")]
        public double? Latitude {get; set;}

        //----------Trail Created At----------
        public DateTime CreatedAt {get; set;}
    }
}

Controllers/TrailController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LostInTheWoods.Factories;
using LostInTheWoods.Models;

namespace LostInTheWoods.Controllers
{
    public class TrailController : Controller
    {
        private readonly TrailFactory trailFactory;
        public TrailController()
        {
            trailFactory = new TrailFactory();
        }
        //-------Home_Page_View-------
        [HttpGet("")]
        public IActionResult Home()
        {
            ViewBag.AllTrails = trailFactory.GetAllTrails();
            return View();
        }
        //-------Single_Trail_View-------
        [HttpGet("trails/{id}")]
        public IActionResult Trail(int id)
        {
            ViewBag.SingleTrail = trailFactory.GetSingleTrail(id);
            return View();
        }
        //-------New_Trail_Page-------
        [HttpGet("trails/new")]
        public IActionResult Add()
        {
            return View();
        }
        //-------Trail_Creation_View-------
        [HttpPost("trails/add")]
        public IActionResult AddTrail(Trail trail)
        {
            if(ModelState.IsValid)
            {
                trailFactory.AddTrail(trail);
                return RedirectToAction("Home");
            }
            return View("Add");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LostInTheWoods</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">LostInTheWoods</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - LostInTheWoods</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Trail/Add.cshtml
@model Trail
<h1 style="text-decoration: underline; font-style: italic;">Add a New Trail</h1>
<div asp-validation-summary="All"></div>
<form asp-action="AddTrail" asp-controller="Trail" method="post">
    <label>Trail Name</label>
    <input style="display: block; margin-bottom: 10px;" asp-for="Name" placeholder="Trail Name">
    <label>Description</label>
    <textarea style="display: block; margin-bottom: 10px;" asp-for="Description" cols="22" rows="3" placeholder="Description"></textarea>
    <label>Trail Length</label>
    <input style="display: block; margin-bottom: 10px;" asp-for="Length" placeholder="Trail Length (mi)">
    <label>Elevation Change (ft)</label>
    <input style="display: block; margin-bottom: 10px;" asp-for="Elevation" placeholder="Elevation Change (ft)">
    <label>Longitude</label>
    <input style="display: block; margin-bottom: 10px;" asp-for="Longitude" placeholder="Longitude">
    <label>Latitude</label>
    <input style="display: block; margin-bottom: 10px;" asp-for="Latitude" placeholder="Latitude">

    <input style="display: block; margin-bottom: 10px;" type="submit" value="Create Record">
</form>
<a style="display: block; margin-top: 10px;" href="/">Return To Home Page</a>

Views/Trail/Home.cshtml
<h1 style="text-decoration: underline; font-style: italic;">Lost in the Woods</h1>
<h3>List of local hiking trails</h3>
<table style="border: 2px solid black; padding: 20px;">
    <thead>
        <tr>
            <th style="border: 2px solid black; padding: 10px;">Trail Name</th>
            <th style="border: 2px solid black; padding: 10px;">Trail Length</th>
            <th style="border: 2px solid black; padding: 10px;">Elevation Change</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var trail in ViewBag.AllTrails)
        {
            <tr>
                <td style="border: 2px solid black; padding: 10px;"><a href="/trails/@trail.ID">@trail.Name</a></td>
                <td style="border: 2px solid black; padding: 10px;">@trail.Length Miles</td>
                <td style="border: 2px solid black; padding: 10px;">@trail.Elevation Feet</td>
            </tr>
        }
    </tbody>
</table>
<button type="button" style="margin-top: 10px;"><a style="color: black; text-decoration: none;" href="/trails/new">Add a new Trail</a></button>

Views/Trail/Trail.cshtml
@foreach(var trail in ViewBag.SingleTrail)
{
    <h1 style="text-decoration: underline; font-style: italic;">@trail.Name</h1>
    <div id="the_trail">
        <h2 style="border: 2px solid black; padding: 10px;">Description</h2>
        <h4 style="margin-left: 5px;">@trail.Description</h4>
        <h2 style="border: 2px solid black; padding: 10px;">Trail Length</h2>
        <h3 style="margin-left: 5px;">@trail.Length miles</h3>
        <h2 style="border: 2px solid black; padding: 10px;">Elevation Change</h2>
        <h3 style="margin-left: 5px;">@trail.Elevation feet</h3>
        @if(@trail.Longitude > 0)
        {
            <h3 style="margin-left: 5px;">Longitude: @trail.Longitude &deg; E</h3>
        }
        @if(@trail.Longitude < 0)
        {
            <h3 style="margin-left: 5px;">Longitude: @trail.Longitude &deg; W</h3>
        }
        @if(@trail.Longitude == 0)
        {
            <h3 style="margin-left: 5px;">Longitude: @trail.Longitude &deg; Prime Meridian</h3>
        }
        @if(@trail.Latitude > 0)
        {
            <h3 style="margin-left: 5px;">Latitude: @trail.Latitude &deg; N</h3>
        }
        @if(@trail.Latitude < 0)
        {
            <h3 style="margin-left: 5px;">Latitude: @trail.Latitude &deg; S</h3>
        }
        @if(@trail.Latitude == 0)
        {
            <h3 style="margin-left: 5px;">Latitude: @trail.Latitude &deg; Prime Meridian</h3>
        }
    </div>
    <a style="display: block; padding-top: 10px;" href="/">Return to Home Page</a>
}